export default {
  CHANGE_ROUTE: 'CHANGE_ROUTE',
  KEY_DOWN: 'KEY_DOWN',
  MOVE_PLAYER: 'MOVE_PLAYER',
  MOVE_PLAYER_TO_POS: 'MOVE_PLAYER_TO_POS',
  MOVE_CURSOR: 'MOVE_CURSOR',
  MOVE_CAMERA_CURSOR: 'MOVE_CAMERA_CURSOR',
  TOGGLE_PAUSE: 'TOGGLE_PAUSE',
  PAUSE: 'PAUSE',
  RESUME: 'RESUME',

  TOGGLE_TRACKING_COLOUR: 'TOGGLE_TRACKING_COLOUR',
  NOTIFY: 'NOTIFY',

  PLAY_SOUND: 'PLAY_SOUND',

  INCREASE_LOST_COUNT: 'INCREASE_LOST_COUNT',
  KILL_MONSTER: 'KILL_MONSTER',
  KILL_STREAK: 'KILL_STREAK',
  ADD_PARTICLE: 'ADD_PARTICLE'
};
